language: java
sudo: false
jdk:
- oraclejdk8
install: true
script: mvn verify -B -e -V sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=$SONAR_TOKEN
env:
  matrix:
  - TEST=ci
matrix:
  fast_finish: true
notifications:
  email: false
